### ISSUE TITLE
WorldGuard Support

### ISSUE THREAD

**Issue by Viylas** [ProSavage/SavageCreepers#1]
Creepers are able to explode in regions with explosion related settings enabled.

Sometimes the nametags don't disappear after using the creepers.

**Comment by prosavage** [comment]
@Driftay Will be taking a look @ this!

**Comment by prosavage** [comment]
Im gonna go ahead and move the repo to our local vcs server, so make issues on there from now on.

**Comment by prosavage** [comment]
Gonna close this, please recreate it on vcs.prosavage.net
